from enum import StrEnum


class EpistemicStatus(StrEnum):
    FACT = "FACT"
    CLAIM = "CLAIM"
    INFERENCE = "INFERENCE"
    HYPOTHESIS = "HYPOTHESIS"
    UNKNOWN = "UNKNOWN"
    ENTITY_UNRESOLVED = "ENTITY_UNRESOLVED"


class EvidenceStance(StrEnum):
    SUPPORT = "SUPPORT"
    REFUTE = "REFUTE"
    NEUTRAL = "NEUTRAL"


class SourceCollectionMode(StrEnum):
    API = "API"
    RSS = "RSS"
    HTTP = "HTTP"
    BROWSER = "BROWSER"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"
    BLOCKED = "BLOCKED"


class IdentityStatus(StrEnum):
    RESOLVED = "RESOLVED"
    REVIEW = "REVIEW"
    UNRESOLVED = "UNRESOLVED"


class IdentityDecisionClass(StrEnum):
    NAME_CONFLICT = "NAME_CONFLICT"
    BIRTH_DATE_CONFLICT = "BIRTH_DATE_CONFLICT"
    CONTEXT_REVIEW = "CONTEXT_REVIEW"
    EXACT_BIRTH_DATE = "EXACT_BIRTH_DATE"
    SAME_STATE_CONTEXT = "SAME_STATE_CONTEXT"
    SHARED_CAREER_ANCHORS = "SHARED_CAREER_ANCHORS"
    EXTERNAL_ID = "EXTERNAL_ID"
    OFFICIAL_CAREER_CONTINUITY = "OFFICIAL_CAREER_CONTINUITY"
    OFFICIAL_BIOGRAPHY_CONTINUITY = "OFFICIAL_BIOGRAPHY_CONTINUITY"


class PublicationStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    PUBLISHED = "PUBLISHED"
    WITHHELD = "WITHHELD"


class SourceRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class MaterializationAction(StrEnum):
    AUTO_CREATE = "AUTO_CREATE"
    AUTO_LINK = "AUTO_LINK"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    HARD_CONFLICT = "HARD_CONFLICT"


class MaterializationDecisionClass(StrEnum):
    AUTHORITATIVE_NEW_IDENTITY = "AUTHORITATIVE_NEW_IDENTITY"
    EXACT_PROVIDER_IDENTITY = "EXACT_PROVIDER_IDENTITY"
    SAME_NAME_AMBIGUITY = "SAME_NAME_AMBIGUITY"
    EXACT_BIRTH_DATE_CONFLICT = "EXACT_BIRTH_DATE_CONFLICT"
    PROVIDER_IDENTITY_CONFLICT = "PROVIDER_IDENTITY_CONFLICT"
    UNSUPPORTED_FEEDER = "UNSUPPORTED_FEEDER"


class IdentityReviewStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class RelationshipStrength(StrEnum):
    WEAK = "WEAK"
    STRONG = "STRONG"


class RelationshipEvidenceType(StrEnum):
    APPOINTMENT = "APPOINTMENT"
    CO_SERVICE = "CO_SERVICE"
    FINANCIAL = "FINANCIAL"
    FAMILY_PUBLIC_RECORD = "FAMILY_PUBLIC_RECORD"
    DIRECT_STATEMENT = "DIRECT_STATEMENT"
    CO_MENTION = "CO_MENTION"


class TalentPoolBucket(StrEnum):
    DIRECT_FEEDER = "DIRECT_FEEDER"
    DOMAIN_SENIOR = "DOMAIN_SENIOR"
    POLITICAL_EXECUTIVE = "POLITICAL_EXECUTIVE"
    TECHNICAL_EXPERT = "TECHNICAL_EXPERT"
    EMERGING = "EMERGING"


class RoleFitStatus(StrEnum):
    EVIDENCED = "EVIDENCED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    GAP = "GAP"


class InstitutionalBodyType(StrEnum):
    PRESIDENTIAL_COMMISSION = "PRESIDENTIAL_COMMISSION"
    PRESIDENTIAL_ADVISORY_BODY = "PRESIDENTIAL_ADVISORY_BODY"
    GOVERNMENT_COMMITTEE = "GOVERNMENT_COMMITTEE"
    TASK_FORCE = "TASK_FORCE"
    SPECIAL_COMMITTEE = "SPECIAL_COMMITTEE"
    PUBLIC_INSTITUTION = "PUBLIC_INSTITUTION"
    POLICY_BANK = "POLICY_BANK"
    STATE_LINKED_COMPANY = "STATE_LINKED_COMPANY"
    PUBLIC_CORPORATION = "PUBLIC_CORPORATION"
    OTHER_PUBLIC_ENTITY = "OTHER_PUBLIC_ENTITY"


class GovernanceRelationType(StrEnum):
    DIRECT_OWNERSHIP = "DIRECT_OWNERSHIP"
    INDIRECT_OWNERSHIP = "INDIRECT_OWNERSHIP"
    LARGEST_SHAREHOLDER = "LARGEST_SHAREHOLDER"
    APPOINTMENT_AUTHORITY = "APPOINTMENT_AUTHORITY"
    RECOMMENDATION_AUTHORITY = "RECOMMENDATION_AUTHORITY"
    BOARD_SELECTION = "BOARD_SELECTION"
    STATUTORY_SUPERVISION = "STATUTORY_SUPERVISION"
    BUDGETARY_SUPERVISION = "BUDGETARY_SUPERVISION"


class CivilServiceCategory(StrEnum):
    CENTRAL_GENERAL = "CENTRAL_GENERAL"
    LOCAL_GENERAL = "LOCAL_GENERAL"
    FOREIGN_SERVICE = "FOREIGN_SERVICE"
    POLICE = "POLICE"
    FIRE = "FIRE"
    TAX = "TAX"
    CUSTOMS = "CUSTOMS"
    AUDIT = "AUDIT"
    CORRECTIONS = "CORRECTIONS"
    IMMIGRATION = "IMMIGRATION"
    OTHER_SPECIFIC = "OTHER_SPECIFIC"


class CivilServiceEventType(StrEnum):
    APPOINTMENT = "APPOINTMENT"
    PROMOTION = "PROMOTION"
    TRANSFER = "TRANSFER"
    SECONDMENT = "SECONDMENT"
    DISPATCH = "DISPATCH"
    RETIREMENT = "RETIREMENT"


class CivilServiceAppointmentRoute(StrEnum):
    REGULAR = "REGULAR"
    SENIOR_CIVIL_SERVICE = "SENIOR_CIVIL_SERVICE"
    OPEN_POSITION = "OPEN_POSITION"
    COMPETITIVE_POSITION = "COMPETITIVE_POSITION"
    FIXED_TERM = "FIXED_TERM"
    EXTERNAL_CAREER = "EXTERNAL_CAREER"


class EmploymentReviewDecision(StrEnum):
    EMPLOYABLE = "EMPLOYABLE"
    APPROVED = "APPROVED"
    RESTRICTED = "RESTRICTED"
    DISAPPROVED = "DISAPPROVED"
    UNKNOWN = "UNKNOWN"


class PublicInstitutionClassification(StrEnum):
    PUBLIC_CORPORATION = "PUBLIC_CORPORATION"
    QUASI_GOVERNMENT = "QUASI_GOVERNMENT"
    OTHER_PUBLIC_INSTITUTION = "OTHER_PUBLIC_INSTITUTION"


class PublicInstitutionExecutiveKind(StrEnum):
    INSTITUTION_HEAD = "INSTITUTION_HEAD"
    STANDING_AUDITOR = "STANDING_AUDITOR"
    STANDING_DIRECTOR = "STANDING_DIRECTOR"
    NON_STANDING_DIRECTOR = "NON_STANDING_DIRECTOR"
    NON_STANDING_AUDITOR = "NON_STANDING_AUDITOR"


class LegalCareerType(StrEnum):
    JUDGE = "JUDGE"
    COURT_PRESIDENT = "COURT_PRESIDENT"
    SUPREME_COURT_JUSTICE = "SUPREME_COURT_JUSTICE"
    JUDICIAL_ADMINISTRATION = "JUDICIAL_ADMINISTRATION"
    PROSECUTOR = "PROSECUTOR"
    CHIEF_PROSECUTOR = "CHIEF_PROSECUTOR"
    PROSECUTOR_GENERAL = "PROSECUTOR_GENERAL"
    MINISTRY_OF_JUSTICE_LEGAL_ROLE = "MINISTRY_OF_JUSTICE_LEGAL_ROLE"
    LAWYER = "LAWYER"
    LAW_FIRM_PARTNER = "LAW_FIRM_PARTNER"
    PUBLIC_DEFENDER_OR_LEGAL_AID = "PUBLIC_DEFENDER_OR_LEGAL_AID"
    CONSTITUTIONAL_COURT_ROLE = "CONSTITUTIONAL_COURT_ROLE"
    LEGAL_ACADEMIC = "LEGAL_ACADEMIC"
    GOVERNMENT_LEGAL_ADVISER = "GOVERNMENT_LEGAL_ADVISER"


class LegalCareerEventType(StrEnum):
    APPOINTMENT = "APPOINTMENT"
    TRANSFER = "TRANSFER"
    PROMOTION = "PROMOTION"
    ASSIGNMENT = "ASSIGNMENT"
    CONCURRENT_APPOINTMENT = "CONCURRENT_APPOINTMENT"
    CONCURRENT_RELEASE = "CONCURRENT_RELEASE"
    RETIREMENT = "RETIREMENT"
    PROFESSIONAL_REGISTRATION = "PROFESSIONAL_REGISTRATION"


class PresidentialPersonnelAction(StrEnum):
    APPOINTED = "APPOINTED"
    NOMINATED = "NOMINATED"
    DESIGNATED = "DESIGNATED"
    COMMISSIONED = "COMMISSIONED"
    ASSIGNED = "ASSIGNED"
    RELEASED = "RELEASED"


class PresidentialRoleScope(StrEnum):
    PRESIDENTIAL_SECRETARIAT = "PRESIDENTIAL_SECRETARIAT"
    NATIONAL_SECURITY_OFFICE = "NATIONAL_SECURITY_OFFICE"
    SPECIAL_ADVISER = "SPECIAL_ADVISER"
    PRESIDENTIAL_COMMISSION = "PRESIDENTIAL_COMMISSION"
    PRESIDENTIAL_TASK_FORCE = "PRESIDENTIAL_TASK_FORCE"


class CrossLaneIdentityEvidenceType(StrEnum):
    EXACT_BIRTH_DATE = "EXACT_BIRTH_DATE"
    EXTERNAL_ID = "EXTERNAL_ID"
    OFFICIAL_CAREER_CONTINUITY = "OFFICIAL_CAREER_CONTINUITY"
    OFFICIAL_BIOGRAPHY_CONTINUITY = "OFFICIAL_BIOGRAPHY_CONTINUITY"
