from enum import StrEnum


class EpistemicStatus(StrEnum):
    FACT = "FACT"
    CLAIM = "CLAIM"
    INFERENCE = "INFERENCE"
    HYPOTHESIS = "HYPOTHESIS"
    UNKNOWN = "UNKNOWN"
    ENTITY_UNRESOLVED = "ENTITY_UNRESOLVED"


class EvidenceStance(StrEnum):
    SUPPORT = "SUPPORT"
    REFUTE = "REFUTE"
    NEUTRAL = "NEUTRAL"


class SourceCollectionMode(StrEnum):
    API = "API"
    RSS = "RSS"
    HTTP = "HTTP"
    BROWSER = "BROWSER"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"
    BLOCKED = "BLOCKED"


class IdentityStatus(StrEnum):
    RESOLVED = "RESOLVED"
    REVIEW = "REVIEW"
    UNRESOLVED = "UNRESOLVED"


class PublicationStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    PUBLISHED = "PUBLISHED"
    WITHHELD = "WITHHELD"


class RelationshipStrength(StrEnum):
    WEAK = "WEAK"
    STRONG = "STRONG"


class RelationshipEvidenceType(StrEnum):
    APPOINTMENT = "APPOINTMENT"
    CO_SERVICE = "CO_SERVICE"
    FINANCIAL = "FINANCIAL"
    FAMILY_PUBLIC_RECORD = "FAMILY_PUBLIC_RECORD"
    DIRECT_STATEMENT = "DIRECT_STATEMENT"
    CO_MENTION = "CO_MENTION"


class TalentPoolBucket(StrEnum):
    DIRECT_FEEDER = "DIRECT_FEEDER"
    DOMAIN_SENIOR = "DOMAIN_SENIOR"
    POLITICAL_EXECUTIVE = "POLITICAL_EXECUTIVE"
    TECHNICAL_EXPERT = "TECHNICAL_EXPERT"
    EMERGING = "EMERGING"


class RoleFitStatus(StrEnum):
    EVIDENCED = "EVIDENCED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    GAP = "GAP"


class InstitutionalBodyType(StrEnum):
    PRESIDENTIAL_COMMISSION = "PRESIDENTIAL_COMMISSION"
    PRESIDENTIAL_ADVISORY_BODY = "PRESIDENTIAL_ADVISORY_BODY"
    GOVERNMENT_COMMITTEE = "GOVERNMENT_COMMITTEE"
    TASK_FORCE = "TASK_FORCE"
    SPECIAL_COMMITTEE = "SPECIAL_COMMITTEE"
    PUBLIC_INSTITUTION = "PUBLIC_INSTITUTION"
    POLICY_BANK = "POLICY_BANK"
    STATE_LINKED_COMPANY = "STATE_LINKED_COMPANY"
    PUBLIC_CORPORATION = "PUBLIC_CORPORATION"
    OTHER_PUBLIC_ENTITY = "OTHER_PUBLIC_ENTITY"


class GovernanceRelationType(StrEnum):
    DIRECT_OWNERSHIP = "DIRECT_OWNERSHIP"
    INDIRECT_OWNERSHIP = "INDIRECT_OWNERSHIP"
    LARGEST_SHAREHOLDER = "LARGEST_SHAREHOLDER"
    APPOINTMENT_AUTHORITY = "APPOINTMENT_AUTHORITY"
    RECOMMENDATION_AUTHORITY = "RECOMMENDATION_AUTHORITY"
    BOARD_SELECTION = "BOARD_SELECTION"
    STATUTORY_SUPERVISION = "STATUTORY_SUPERVISION"
    BUDGETARY_SUPERVISION = "BUDGETARY_SUPERVISION"


class CivilServiceCategory(StrEnum):
    CENTRAL_GENERAL = "CENTRAL_GENERAL"
    LOCAL_GENERAL = "LOCAL_GENERAL"
    FOREIGN_SERVICE = "FOREIGN_SERVICE"
    POLICE = "POLICE"
    FIRE = "FIRE"
    TAX = "TAX"
    CUSTOMS = "CUSTOMS"
    AUDIT = "AUDIT"
    CORRECTIONS = "CORRECTIONS"
    IMMIGRATION = "IMMIGRATION"
    OTHER_SPECIFIC = "OTHER_SPECIFIC"


class CivilServiceEventType(StrEnum):
    APPOINTMENT = "APPOINTMENT"
    PROMOTION = "PROMOTION"
    TRANSFER = "TRANSFER"
    SECONDMENT = "SECONDMENT"
    DISPATCH = "DISPATCH"
    RETIREMENT = "RETIREMENT"


class CivilServiceAppointmentRoute(StrEnum):
    REGULAR = "REGULAR"
    SENIOR_CIVIL_SERVICE = "SENIOR_CIVIL_SERVICE"
    OPEN_POSITION = "OPEN_POSITION"
    COMPETITIVE_POSITION = "COMPETITIVE_POSITION"
    FIXED_TERM = "FIXED_TERM"
    EXTERNAL_CAREER = "EXTERNAL_CAREER"


class EmploymentReviewDecision(StrEnum):
    EMPLOYABLE = "EMPLOYABLE"
    APPROVED = "APPROVED"
    RESTRICTED = "RESTRICTED"
    DISAPPROVED = "DISAPPROVED"
    UNKNOWN = "UNKNOWN"


class PublicInstitutionClassification(StrEnum):
    PUBLIC_CORPORATION = "PUBLIC_CORPORATION"
    QUASI_GOVERNMENT = "QUASI_GOVERNMENT"
    OTHER_PUBLIC_INSTITUTION = "OTHER_PUBLIC_INSTITUTION"


class PublicInstitutionExecutiveKind(StrEnum):
    INSTITUTION_HEAD = "INSTITUTION_HEAD"
    STANDING_AUDITOR = "STANDING_AUDITOR"
    STANDING_DIRECTOR = "STANDING_DIRECTOR"
    NON_STANDING_DIRECTOR = "NON_STANDING_DIRECTOR"
    NON_STANDING_AUDITOR = "NON_STANDING_AUDITOR"
